name: Deploy Vite React App to Kubernetes

on:
  push:
    branches:
      - main
      - master

env:
  DOCKERHUB_USERNAME: tinystepsd3v
  IMAGE_NAME: ts-react-client

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.create_tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create image tag
        id: create_tag
        run: echo "IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c1-7)-$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.create_tag.outputs.IMAGE_TAG }}

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment:
      name: development
      url: https://dev.tinystepscdc.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Development
        run: |
          kubectl apply -f k8s/cluster-issuer.yml
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
          kubectl apply -f k8s/ingress-dev.yml
          kubectl set image deployment/ts-react-client ts-react-client=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.IMAGE_TAG }}
          kubectl rollout status deployment/ts-react-client

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://tinystepscdc.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Production
        run: |
          kubectl apply -f k8s/cluster-issuer.yml
          kubectl apply -f k8s/deployment.yml
          kubectl apply -f k8s/service.yml
          kubectl apply -f k8s/ingress-prod.yml
          kubectl set image deployment/ts-react-client ts-react-client=${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.IMAGE_TAG }}
          kubectl rollout status deployment/ts-react-client
